### ISSUE TITLE
Slow destroy

### ISSUE THREAD

**Issue by Craga89** [qTip2/qTip2#468]
Fix up .cleanData loop causes by overriding $.ui methods

See: http://craigsworks.com/projects/forums/thread-qtip-slow-on-destroy
Test case: http://jsfiddle.net/wpjUy/2/

**Comment by purefan** [comment]
I just ran into this issue today, the number of nodes with qtip is around 160
![screen shot 2015-02-17 at 13 47 51](https://cloud.githubusercontent.com/assets/315880/6228399/bf70a42e-b6ab-11e4-8da2-5e1efe595a1c.png)
Here is the code that Im using to bind:
```
var cacheNodes = $('[title!=""]'), 
                targetNodes = cacheNodes.filter(function (index) {
                    return typeof $(cacheNodes[index]).attr('title') !== 'undefined';
                });
                window.console.log('targetNodes.length: ' + targetNodes.length);
                $(targetNodes).qtip({
                    position: {
                        viewport: $('body'),
                        adjust: {
                            method: 'flipinvert none'
                        }
                    }
                });
```

This is in an AngularJS app, and the problem happens when going to another controller.

These are the metrics from Chrome's dev tools' Profiler:
With qTip: ~350ms
Without qTip: ~50ms

(ran 3 tests for each case)
